Introduced real command line options (not just positional parameters)

diff --git a/mqtt-grep-color b/mqtt-grep-color
--- a/mqtt-grep-color
+++ b/mqtt-grep-color
@@ -1,4 +1,5 @@
 #!/bin/sh
+# shellcheck shell=ash
 
 # Usage: mqqtgrep <expr> <topic>
 # subscribe to the MQTT "topic" (Default: #) and colorize it, optionally grepping for "expr"
@@ -7,18 +8,46 @@
 # For more information see project "mqtt-grep-color" on GitHub.
 
 set -o noglob     # file name globbing is neither needed or nor wanted
+set -f
 set -o noclobber  # disable for security reasons
 
-# Parameters:
-grepexp="${1:-[\}{ ]|\[\]|\[{|\}\]}" # colorize the }{, if no other grep expression given; space must be there!
-topic="${2:-#}"        # use '#' as MQTT topic, if nothing else given
-optmqqt="${3:--h localhost}"  # configure your host here or in $HOME/.config/mosquitto_sub
-stdbufcmd=""
+grepexp="[\}{ ]|\[\]|\[\{|\}\]" # colorize the }{, if no other grep expression given; space must be there!
+topic="#"        # use '#' as MQTT topic, if nothing else given
+mqtthost="-v"     # use "-v" to make sure mqtthost     is not an empty option
 
-# Other settings and helpers:
+scriptname="${0##*/}"
+
+while getopts "?e:h:t:d" opt      
+do
+    case "$opt" in
+    \?) echo "Usage: $scriptname -e expr -h host -d -t topic  othermosquittoopts" 1>&2
+        exit 1
+        ;;
+    e)  grepexp="$OPTARG"
+		;;
+    h)  mqtthost="$OPTARG" # configure broker host here or in $HOME/.config/mosquitto_sub
+        if [ "$mqtthost" = "test" ] ; then
+            mqtthost="-h test.mosquitto.org"
+        else
+            mqtthost="-h $( echo $mqtthost | tr -d ':()"^%$ \r\000-\011\013-\037')" # clean up for sec purposes
+        fi
+        ;;
+    t)  topic=$( echo "$OPTARG" | sed -e 's:/$:/\#:' ) # as a service add \# to a trailing /
+        ;;
+    d)  set -x
+        ;;
+    esac
+done
+
+shift "$((OPTIND-1))"   # Discard the rest of the options and sentinel --
+
+# Prepare settings and helpers such as stdbuf:
+stdbufcmd=""
 stdbufcmd_tr=$( command -v stdbuf ) && stdbufcmd_tr="$stdbufcmd_tr --output=L" # use stdbuf for tr if available
-[ -z "$stdbufcmd_tr" ] && echo "$0: Warning: Please install stdbuf!" 1>&2
+[ -z "$stdbufcmd_tr" ] && echo "$0: Warning: Install stdbuf for better line buffering!" 1>&2
+
 { grep --help 2>&1 | grep -q BusyBox ; } && BUSYBOX="yes" && stdbufcmd="$stdbufcmd_tr" # ... and stdbuf also for grep if on BusyBox
+
 # for BusyBox grep - it cannot colorize - and the option line-buffered is also missing.
 GREPOPTS="-E" && [ -z "$BUSYBOX" ] && GREPOPTS="$GREPOPTS --text --color=always --line-buffered"
 
@@ -27,8 +56,9 @@ yellow="01;33"; red="01;31"; green="01;32"; blue="01;34" ; purple="01;35"
 
 # These are the following four steps for processing the MQTT stream: 0. remove some non-printable stuff, 1. color the topic red,
 # 2. put the time in front, 3. color the time, 4. color the optional expression or curly brackets etc by default.
-{ mosquitto_sub $optmqqt -v -t "$topic"                   ; }           \
-|                     $stdbufcmd_tr   tr '\r\000-\011\013-\037' ' '     \
+# N.B. No double quotes around ""
+{ mosquitto_sub $mqtthost -v -t "$topic" "$@"       ; }   \
+|                     $stdbufcmd_tr  tr '\r\000-\011\013-\037' ' '    \
 | GREP_COLOR="$red"    $stdbufcmd    grep $GREPOPTS -e '^[^ ]+| '      \
 | awk -- '{ print strftime("%H:%M:%S ") $0 ; fflush() ; next } '       \
 | GREP_COLOR="$yellow" $stdbufcmd    grep $GREPOPTS -e "^..:..:.."   \
